name: rad_bench_1_0_aplha
publish_to: none
description: Rad JS-Benchmarks
version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  rad:
    git:
      url: https://github.com/erlage/rad.git
      ref: v1.6.0
      path: packages/rad

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
